## Before we move forward, let's refresh basic linear algebra concepts and operations:

<img src="../img/linear_algebra/scalar_vector_matrix.png" width="750"/>

### Scalar
Scalars are mathematical entities which have only a magnitude (and no direction). Physical examples include mass and energy.

### Vector
**Definition**: A vector is a list of numbers. There are (at least) two ways to interpret what this list of numbers mean:

**One way:**
Think of the vector as being a point in a space. Then this list of numbers is a way of identifying that point in space, where each number represents the vector’s component that dimension.

**Another way:**
Think of a vector is a **magnitude** and a **direction**, e.g. a quantity like velocity (“the fighter jet’s velocity is 250 mph north-by-northwest”). In this way of think of it, a vector is a **directed arrow pointing** from the origin to the end point given by the list of numbers.

**Example:**
$a^{->} = [4, 3]$. Graphically, you can think of this vector as an arrow in the x-y (two dimensional space) plane, pointing from the origin to the point at x=3, y=4

<img src="../img/linear_algebra/vector_visual_representation.png" width="350"/>

**Vector and scalar operations:**

All binary operations between a vector and a scalar are accomplished by operating on each entry in the vector individually. The following shows vector-scalar addition as well as vector-scalar multiplication:

Addition:
$ \begin{align}
    -3 +
        \begin{bmatrix}
           {1} \\
           {5} \\
           {0}
         \end{bmatrix}
         =
         \begin{bmatrix}
           {-2} \\
           {-2} \\
           {-3}
         \end{bmatrix}
  \end{align}$

Multiplication:
$ \begin{align}
    -3 \cdot
        \begin{bmatrix}
           {1} \\
           {5} \\
           {0}
         \end{bmatrix}
         =
         \begin{bmatrix}
           {-3} \\
           {-15} \\
           {0}
         \end{bmatrix}
  \end{align}$

### Scalar multiplication
The term scalar multiplication refers to the product of a real number and a matrix. In scalar multiplication, each entry in the matrix is multiplied by the given scalar.
<img src="../img/linear_algebra/matrices_and_scalar_multiplication.png" width="250"/>

In [5]:
# Scalar to vector multiplication
scalar = 2
vector = [1, 5, 0]
print(list(map(lambda s: s * scalar, vector)))

[2, 10, 0]


In [6]:
# Scalar to matrix multiplication
import numpy as np

scalar = 2
m = [[5, 2],
     [3, 1]]

matrix_res = np.zeros((len(m), len(m)), dtype=int)

for i in range(len(m)):
    for j in range(len(m)):
        matrix_res[i][j] = scalar * m[i][j]
print(matrix_res)

[[10  4]
 [ 6  2]]


### Matrices addition
A matrix, like a vector, is also a collection of numbers. The difference is that a matrix is a table of numbers rather than a list. (In fact, you can think of vectors as matrices that happen to only have one column or one row.)

**Matrix addition and subtraction:**
<img src="../img/linear_algebra/matrices_addition_substraction.png" width="250"/>

[Check your understanding](https://www.khanacademy.org/math/precalculus/x9e81a4f98389efdf:matrices/x9e81a4f98389efdf:adding-and-subtracting-matrices/a/adding-and-subtracting-matrices)

In [7]:
# Addition matrices
def matrices_addition(m1, m2):
    matrix_res = np.zeros((len(m1), len(m2)), dtype=int)
    for row in range(len(m2)):
        for col in range(len(m2)):
            matrix_res[row][col] = m1[row][col] + m2[row][col]
            print(" %i + %i = %i" % (m1[row][col], m2[row][col], m1[row][col] + m2[row][col]))
    return matrix_res


a = [[4, 8],
     [3, 7]]

b = [[1, 0],
     [5, 2]]

print(matrices_addition(a, b))

 4 + 1 = 5
 8 + 0 = 8
 3 + 5 = 8
 7 + 2 = 9
[[5 8]
 [8 9]]


### Matrix and vector multiplication, widely use in regression implementation

A Matrix and a vector can be multiplied only if the number of columns of the matrix and the the dimension of the vector have **the same size.**

<img src="../img/linear_algebra/matrix_vector_product.png" width="500"/>

In [8]:
# Matrix to vector multiplication
def matrix_vector_multiplication(m, vector):
    vector_res = np.zeros((len(m), 1), dtype=int)
    for i in range(3):
        for j in range(2):
            vector_res[i][0] += m[i][j] * vector[j][0]
    return vector_res


m = [[1, 2],
     [3, 4],
     [5, 6]]

vector = [[1],
          [2]]

print(matrix_vector_multiplication(m, vector))

[[ 5]
 [11]
 [17]]


### Matrices multiplication
refers to the product of two matrices. The resulting matrix, known as the matrix product, has the number of rows of the first and the number of columns of the second matrix. The product of matrices A and B is denoted as AB.

<img src="../img/linear_algebra/matrices_multiplication.png" width="450"/>


[Check your understanding with matrices](https://www.khanacademy.org/math/precalculus/x9e81a4f98389efdf:matrices/x9e81a4f98389efdf:multiplying-matrices-by-matrices/a/multiplying-matrices)

In [ ]:
# Multiply each element of row matrix 1 to the each element of the column matrix 2.
# check yourself https://keisan.casio.com
def matrices_multiplication(m1, m2):
    matrix_res = np.zeros((len(m1), len(m2)), dtype=int)

    for i in range(len(m1)):
        for col in range(len(m2)):
            for row in range(len(m2)):
                matrix_res[i][col] += m1[i][row] * m2[row][col]
                print(" %i * %i = %i" % (m1[i][row], m2[row][col], m1[i][row] * m2[row][col]))
    return matrix_res


a = [[1, 2],
     [3, 4]]

b = [[5, 6],
     [7, 8]]

print(matrices_multiplication(a, b))